version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
    volumes:
      - ./backend/app:/app
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000
